### ISSUE TITLE
Support multivalue metric names

### ISSUE THREAD

**Issue by kinnarr** [metricq/metricq-grafana#20]
#2 added support for multivalue aggregates, now we need support for multivalue metric names

**Comment by tilsche** [comment]
Can we estimate how much effort this is?

**Comment by kinnarr** [comment]
Should be very easy. I just need to know what format is used to represent the multivalue as string. Is it `(value1|value2|value3)`?

**Comment by kinnarr** [comment]
This should also support metrics like `test.(value1|value2).rate`
