### ISSUE TITLE
Allow fetching of bulk-medata

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-grafana#29]
We need a way to search get the metadata for a `/search` request.
This would probably be a parameter for `search`.
One could also think of extending the selector for `/metadata`, but I think that is more dangerous to break existing stuff.

This is pretty important for webview right now.

**Comment by kinnarr** [comment]
Is the presence of `metadata` in the query string sufficient to enable this feature, or should `metadata=0` be supported to disable metadata (which would be the default anyway).

**Comment by kinnarr** [comment]
Nevermind, `/search` is a POST view and already uses json data for the target, so `metadata` will also be a json field.
