### ISSUE TITLE
Make /search?limit configurable

### ISSUE THREAD

**Issue by tilsche** [metricq/metricq-grafana#30]
While we're at enhancing `/search` for #29 it's probably a good idea to make the limit configurable, but keep the default of `None` / `100` for `selector` and `infix` requests respectively.

**Comment by kinnarr** [comment]
Should it be possible for `infix` to set the limit to `None`?

**Comment by tilsche** [comment]
> Should it be possible for `infix` to set the limit to `None`?

Yes. I suppose you want it to mean "unlimited". But it can be careful to distinguish `None` from not given at times. Maybe use `None` for default and `false` for unlimited in the first place.
