### ISSUE TITLE
Search for subsequences

### ISSUE THREAD

**Issue by bmario** [metricq/metricq-grafana#4]
We should be able to search for subsequences in the routing key.

Query | Matches `elab.bakha.power` | Matches `elab.ariel.power`
------|------------|------------
`ariel` | no | yes
`power` |  yes | yes
`elbapo` | yes | yes
`elbhpo` | yes | no
`.ar` | yes | yes

From [here](https://stackoverflow.com/questions/24017363/how-to-test-if-one-string-is-a-subsequence-of-another):
```
def is_subseq(x, y):
    it = iter(y)
    return all(c in it for c in x)
```

**Comment by kinnarr** [comment]
Except for `elbapo` and `elbhpo` this should be already supported

**Comment by bmario** [comment]
Yes, that's the point. Also, `.ar` only matches the `elab.ariel.power` metric, doesn't it?

**Comment by bmario** [comment]
No fuzzy search support in couchdb, which would be fast enough to deliver this, so I'm closing it
